events { worker_connections 1024; }
http {
    # Dùng DNS của Azure để Nginx tự phân giải domain nội bộ
    resolver 168.63.129.16 valid=5s;

    server {
        listen 80;

        location / {
            # Tên miền của Store UI trên Azure
            set $frontend "app-store-ui-dev-gwddamaqddfda8av.japaneast-01.azurewebsites.net";
            proxy_pass http://$frontend;
            proxy_set_header Host $frontend;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/ {
            # Tên miền của API Backend trên Azure
            set $backend "app-products-api-dev-v2-bjenfgbze8fufebs.japaneast-01.azurewebsites.net";
            proxy_pass http://$backend/api/;
            proxy_set_header Host $backend;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}